2020-10-28 14:46:30,126 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:46:33,144 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:46:36,155 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:46:39,175 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:46:42,198 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:46:45,222 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:46:48,238 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:46:51,248 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:46:54,257 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:46:57,265 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:46:59,532 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:47:00,481 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:47:00,584 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:47:03,568 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:47:06,578 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:47:09,590 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:47:12,605 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:47:15,614 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:47:18,656 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:47:21,713 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:47:24,722 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
2020-10-28 14:47:27,729 Host resolution error: [Failure instance: Traceback: <class 'TypeError'>: argument should be integer or bytes-like object, not 'str'
/usr/local/lib/python3.8/dist-packages/twisted/web/http.py:790:requestReceived
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:132:process
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:303:addCallback
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:293:addCallbacks
--- <exception caught here> ---
/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py:575:_runCallbacks
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:90:handleHostResolvedSuccess
/usr/local/lib/python3.8/dist-packages/sslstrip/ClientRequest.py:68:getPathFromUri
]
